version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
            - php_socket:/var/run/php
        env_file:
            - .env.docker
        depends_on:
            - db
            - redis
        entrypoint: ["/var/www/docker/entrypoint.sh"]

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "800:80"  # http://localhost:800
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www
            - php_socket:/var/run/php
        depends_on:
            - app

    db:
        image: mariadb:10.11
        container_name: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: gp
            MARIADB_USER: root
            MARIADB_PASSWORD: root
        ports:
            - "33060:3306"
        volumes:
            - db_data:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "63790:6379"
        restart: always

volumes:
    db_data:
    php_socket:
